const ActionTypes = {
  APP_CHANGE_EDITING_WORD: 0x00,
  APP_CLOSE_DIALOG: 0x01,
  APP_OPEN_DIALOG: 0x02,
  APP_LOCK_DIALOG: 0x03,
  APP_UNLOCK_DIALOG: 0x04,
  APP_SELECT_WORD: 0x05,
  APP_SET_WORD_TYPE_REFS: 0x06,
  APP_PENDING_SWITCH_WORD: 0x07,

  SEARCH_SET_SUGGESTIONS: 0x10,
  SEARCH_SET_SUGGESTION_USE: 0x11,

  EDITOR_ADD_DEFINITION: 0x20,
  EDITOR_DELETE_DEFINITION: 0x21,
  EDITOR_EDIT_DEFINITION: 0x22,
  EDITOR_ADD_EXAMPLE: 0x23,
  EDITOR_DELETE_EXAMPLE: 0x24,
  EDITOR_EDIT_EXAMPLE: 0x25,
  EDITOR_EDIT_FIELD: 0x26,
  EDITOR_ADD_RELATION: 0x27,
  EDITOR_DELETE_RELATION: 0x28,
  EDITOR_PUT_WORD: 0x29,
  EDITOR_RESET: 0x2a,
};

export default ActionTypes;
